name: CI/CD desde cero

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas (si existen)
      run: npm test || echo "No hay tests definidos"

    - name: Build del proyecto (si existe)
      run: npm run build || echo "No hay build definido"

    - name: Deploy automático
      if: success()
      run: echo "Deploy realizado correctamente 🚀"
