name: CI/CD seguro

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Ver archivos
      run: ls -la

    - name: Instalar dependencias
      run: |
        if [ -f package.json ]; then
          npm install
        else
          echo "No es proyecto Node"
        fi

    - name: Ejecutar tests
      run: |
        if grep -q '"test"' package.json; then
          npm test
        else
          echo "No hay tests"
        fi

    - name: Build
      run: |
        if grep -q '"build"' package.json; then
          npm run build
        else
          echo "No hay build"
        fi

    - name: Deploy
      if: success()
      run: echo "Deploy OK 🚀"
